spring:
  application:
    name: auth-api
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: ${JWT_EXPIRATION_TIME}
